### ISSUE TITLE
Copying code snippets will include line numbers

### ISSUE THREAD

**Issue by fnagel** [TYPO3-Documentation/sphinx_typo3_theme#184]
I've noticed its not possible to copy code snippets without copying the line numbers? 
Is this an EXT:news issue or a general one?

https://docs.typo3.org/p/georgringer/news/10.0/en-us/Tutorials/BestPractice/Routing/Index.html#id3

Reference: https://typo3.slack.com/archives/C028JEPJL/p1676383069691979

**Comment by sypets** [comment]
Same on official documentation pages.

**Comment by marble** [comment]
Related to #149

**Comment by DavidBruchmann** [comment]
related to [#207](https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/207), here it's more specific though as it's related to sphinx.

**Comment by marble** [comment]
Fixed with TYPO3 Theme 4.7.10 which is used in DRC v3.0.0

**Comment by fnagel** [comment]
Sorry for the late response. Vacation and the aftermath of it caused a delay ;-)

Afaics this is still an issue, at least for older EXT:news docs, see https://docs.typo3.org/p/georgringer/news/11.0/en-us/Tutorials/BestPractice/Routing/Index.html

It works as expected in newer and latest version:
* https://docs.typo3.org/p/georgringer/news/11.1/en-us/Tutorials/BestPractice/Routing/Index.html
* https://docs.typo3.org/p/georgringer/news/11.2/en-us/Tutorials/BestPractice/Routing/Index.html
* https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/BestPractice/Routing/Index.html

Not sure if it was only possible to fix this for newer releases. Just wanted to give you some feedback.

FYI @marble

**Comment by brotkrueml** [comment]
The manuals of older versions have to be re-rendered (not only EXT:news, but also all other extension which are available of docs.typo3.org). As this is not feasible we have to live with that.

**Comment by fnagel** [comment]
@brotkrueml Ok, thanks for letting me know!

**Comment by brotkrueml** [comment]
Yes, but this only is for EXT:news, not for all the other extension manuals out there, which have the line numbers in the clipboard when copying. This is what I meant.

**Comment by brotkrueml** [comment]
It is worth the resources? Just for old and outdated manuals? Clearly we can do it. We should then also think about when to re-render all manuals for all versions (from the docs team and 3rd-party extensions) for future changes. IMHO it is a waste of time and resources for outdated versions and manuals. But feel free to care about it and proceed.
